# Model

In [26]:
m = {
    ## Variables
    'total_emission_sates': 3, # valores observaveis
    'total_hidden_sates': 2, # estados ocultos 
    
    ## Probabilities
    'transition_prob': [ # nxn
        [.75, .25],
        [.35, .65]
    ],
    'emission_prob': [ # nxm
        [.7, .2, .1],
        [.3, .1, .6]
    ],
    'inital_prab': [.8, .2] # 1xn
}

# Gerador de Trajetória

In [27]:
from sim import generate_trajectory

O, S = generate_trajectory(100, **m)

In [33]:
m_init = {
    'total_emission_sates': 3,
    'total_hidden_sates': 2,
    'transition_prob': [
        [.1, .9],
        [.9, .1]
    ],
    'emission_prob': [
        [.35, .3, .35],
        [.35, .3, .35]
    ],
    'inital_prab': [.5, .5]
}

In [34]:
from hmm import HiddenMarkovModel
import numpy as np

hmm = HiddenMarkovModel(3, 2, random_state=0)
hmm.fit(O, initial_model=m_init)
model = hmm.get_model()

print("Real", m)
print("Esti", model)
np.log(hmm.model.p())

Real {'total_emission_sates': 3, 'total_hidden_sates': 2, 'transition_prob': [[0.75, 0.25], [0.35, 0.65]], 'emission_prob': [[0.7, 0.2, 0.1], [0.3, 0.1, 0.6]], 'inital_prab': [0.8, 0.2]}
Esti {'total_emission_sates': 3, 'total_hidden_sates': 2, 'transition_prob': [[0.1, 0.9], [0.9, 0.1]], 'emission_prob': [[0.53, 0.19, 0.28], [0.53, 0.19, 0.28]], 'inital_prab': [0.5, 0.5]}


-100.8454802914786

In [36]:
import numpy as np
from hmmlearn import hmm

remodel = hmm.CategoricalHMM(n_components=2, n_features=3, random_state=0, n_iter=100, init_params="mcs")
remodel.transmat_ = m_init['transition_prob']
remodel.emissionprob_ = m_init['emission_prob']
remodel.startprob_ = m_init['inital_prab']



remodel.fit([O])
print(np.round_(remodel.transmat_, 2))
print(remodel.emissionprob_)
print(remodel.startprob_)

remodel.score([O])

Even though the 'startprob_' attribute is set, it will be overwritten during initialization because 'init_params' contains 's'


[[0.1 0.9]
 [0.9 0.1]]
[[0.52726017 0.19125721 0.28148262]
 [0.53273615 0.18874448 0.27851938]]
[0.44298989 0.55701011]


-100.84417933551052